"""refactor  doc table

Revision ID: e3e8b2fc5303
Revises: 864cf80c00f1
Create Date: 2025-12-18 13:38:01.203192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID as PG_UUID


# revision identifiers, used by Alembic.
revision: str = 'e3e8b2fc5303'
down_revision: Union[str, Sequence[str], None] = '864cf80c00f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. drop the old primary-key constraint
    op.drop_constraint('documents_pkey', 'documents', type_='primary')

    # 2. change the column type, discarding old values
    op.execute('ALTER TABLE documents ALTER COLUMN id DROP DEFAULT')
    op.alter_column('documents', 'id',
                    existing_type=sa.Integer,
                    type_=PG_UUID(as_uuid=True),
                    postgresql_using='gen_random_uuid()',  # or uuid_generate_v4()
                    nullable=False)

    # 3. create new PK
    op.create_primary_key('documents_pkey', 'documents', ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='unique')
    op.alter_column('documents', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
