"""refactor  doc table

Revision ID: f0144ba9b242
Revises: e3e8b2fc5303
Create Date: 2025-12-18 14:28:10.414164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0144ba9b242'
down_revision: Union[str, Sequence[str], None] = 'e3e8b2fc5303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('uq_user_single_docs'), table_name='documents', postgresql_where="(((file_type)::text = ANY ((ARRAY['cv'::character varying, 'cover_letter'::character varying])::text[])) AND (deleted_at IS NULL))")
    op.create_index(op.f('ix_documents_file_type'), 'documents', ['file_type'], unique=False)
    op.create_unique_constraint(None, 'documents', ['id'])
    # ### end Alembic commands ###
    op.execute("""
        CREATE UNIQUE INDEX uq_user_single_docs
        ON documents (user_id, file_type)
        WHERE file_type IN ('cv', 'cover_letter')
        AND deleted_at IS NULL;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_index(op.f('ix_documents_file_type'), table_name='documents')
    op.create_index(op.f('uq_user_single_docs'), 'documents', ['user_id', 'file_type'], unique=True, postgresql_where="(((file_type)::text = ANY ((ARRAY['cv'::character varying, 'cover_letter'::character varying])::text[])) AND (deleted_at IS NULL))")
    op.alter_column('documents', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
